---
driver:
  name: vagrant
  customize:
    memory: 2500
#    cableconnected1: 'on'

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
       - 'recipe[apt::default]'
       - 'recipe[java::default]'
       - 'recipe[ambari::default]'
       - 'recipe[ambari::postgres_server_embedded_setup]'
       - 'recipe[ambari::ambari_server_setup]'
       - 'recipe[ambari::ambari_views_setup]'
    attributes: {
      java: {
        oracle: {
          accept_oracle_download_terms: true,
          jce: {
            enabled: true
          }
        },
        jdk_version: 8,
        install_flavor: oracle,
        accept_license_agreement: true,
        set_default: true
      }
    }
    driver:
      box: bento/ubuntu-14.04
      network:
      - [ "private_network" , { ip : "10.0.100.31" } ]
      - [ "forwarded_port" , { guest : 8080, host : 8080 } ]
suites:
  - name: default
    attributes:
