---
driver:
  name: vagrant
  customize:
    memory: 2500
#    cableconnected1: 'on'

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - 'recipe[java::default]'
      - recipe[ambari_metrics::default]
    attributes: {
      java: {
        oracle: {
          accept_oracle_download_terms: true,
          jce: {
            enabled: true
          }
        },
        jdk_version: 8,
        install_flavor: oracle,
        accept_license_agreement: true,
        set_default: true
      }
    }
    driver:
      box: bento/ubuntu-14.04
      network:
      - [ "forwarded_port" , { guest : 3000, host : 3000 } ]
