# -*- mode: yaml-mode -*-
---
driver:
  name: vagrant

driver:
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk -v 1.2
  chef_omnibus_root: /opt/chefdk
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>
  client_rb:
    no_proxy: localhost
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['https_proxy'] %>

platforms:
  - name: ubuntu-14.04

suites:
  - name: bach_repository
    run_list:
      - recipe[apt]
      - recipe[bach_repository_test::default]
      - recipe[bach_repository]
      - recipe[export-node::default]
    attributes: {
      bach: {
        repository: {
          repo_directory: "/test/repo_dir",
          bundler_bin: "/opt/chefdk/embedded/bin/bundle",
          gem_bin: "/opt/chefdk/embedded/bin/gem"
        }
      }
    }
