# -*- mode: yaml-mode -*-
---
driver:
  dockerfile: test/Dockerfile
  name: docker
  proxy: <%= ENV['http_proxy'] %>

provisioner:
  name: chef_zero
  client_rb:
    no_proxy: localhost
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['https_proxy'] %>

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[bach_common::kitchen-fixes]
      - recipe[bach_repository]
    attributes:
