---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: "12.19.36"
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.2
    driver:
     box: bento/ubuntu-14.04
     network:
     - [ "private_network" , { ip : "10.0.100.27" } ]
     - [ "forwarded_port" , { guest : 8080, host : 8080 } ]

suites:
  - name: default
    run_list:
      - recipe[bach_ambari_wrapper::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
